Avoid Python detection loops
find_python now checks more in depth what Python version it returns, so
its users no longer need any looping logic.

It currently only checks for the wx library presence, but the that could
be easily extended.

diff --git a/bash/find_python b/bash/find_python
--- a/bash/find_python
+++ b/bash/find_python
@@ -1,44 +1,5 @@
 #!/usr/bin/env bash
 
-# Python versions
-search_python () {
-	while [ "$POL_PYTHON" != "none" ]; do
-		if [ "$POL_PYTHON" ]; then
-			echo -n "Looking for $POL_PYTHON... " 1>&2
-			if [ "$(which $POL_PYTHON)" ]; then
-				local Version=$($POL_PYTHON --version 2>&1 |tail -n 1|sed -e 's/^Python //')
-				echo -n "$Version - " 1>&2
-				case "$Version" in
-				    2.6|2.6.*|2.7|2.7.*)
-				        echo "selected" 1>&2
-					return
-					;;
-				    2.5|2.5.*)
-				        # Compatibility broken a while ago
-					echo "skipped" 1>&2
-					;;
-				    3.*)
-					# Not supported because of wxPython
-					echo "skipped" 1>&2
-					;;
-				    *)
-					echo "unexpected version" 1>&2
-					;;
-               			esac
-			else
-				echo "" 1>&2
-			fi
-		fi
-
-		# list of interpreter names to try, in order
-		next_python "python"
-		next_python "python2.7"
-		next_python "python2.6"
-		next_python "python2"
-		next_python "none"
-	done
-}
-
 next_python () {
 	if [ "$POL_PYTHON" = "$1" ]; then
 		# will pick the next one
@@ -48,11 +9,57 @@ next_python () {
 	fi
 }
 
-if [ -z "$POL_PYTHON" ]; then
-	search_python
+search_python () {
+	POL_PYTHON=""
+	while true; do
+		# list of interpreter names to try, in order
+		next_python "python"
+		next_python "python2.7"
+		next_python "python2.6"
+		next_python "python2"
+		next_python "none"
+	
+		if [ "$POL_PYTHON" = "none" ]; then
+			echo "Please install python before trying to run this program" 1>&2
+			return 1
+		fi                   
+	
+		echo -n "Looking for $POL_PYTHON... " 1>&2
+		if [ "$(which $POL_PYTHON)" ]; then
+			local Version=$($POL_PYTHON --version 2>&1 |tail -n 1|sed -e 's/^Python //')
+			echo -n "$Version - " 1>&2
+			case "$Version" in
+			    2.6|2.6.*|2.7|2.7.*)
+	                        if test_python; then
+				        echo "selected" 1>&2
+					return 0
+				fi
+				echo "failed tests" 1>&2
+				;;
+			    2.5|2.5.*)
+			        # Compatibility broken a while ago
+				echo "skipped" 1>&2
+				;;
+			    3.*)
+				# Not supported because of wxPython
+				echo "skipped" 1>&2
+				;;
+			    *)
+				echo "unexpected version" 1>&2
+				;;
+			esac
+		else
+			# Interpreter name not found
+			echo "" 1>&2
+		fi
+	done
+}
 
-	if [ "$POL_PYTHON" = "none" ]; then
-		echo "Please install python before trying to run this program" 1>&2
-		exit 1
-	fi
-fi
+test_python () {
+    cat <<'_EOF_' > "$POL_USER_ROOT/tmp/testlibs.py"
+import wx
+_EOF_
+    "$POL_PYTHON" "$POL_USER_ROOT/tmp/testlibs.py"
+}
+
+search_python
